# Render Configuration File
# Documentation: https://render.com/docs/deploy-django

services:
  - type: web
    name: truckbrand
    env: python
    python:
      version: "3.10.12"
    buildCommand: |
      python -m pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt --no-cache-dir --force-reinstall
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "ecommerce.settings"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: truckbrand-db
          property: connectionString
      # Email settings
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "true"
      - key: EMAIL_HOST_USER
        value: "your-email@gmail.com"  # Update with your email
      - key: EMAIL_HOST_PASSWORD
        value: "your-app-password"     # Use App Password if using Gmail
      - key: DEFAULT_FROM_EMAIL
        value: "your-email@gmail.com"  # Update with your email
    plan: free
    numInstances: 1
    healthCheckPath: /
    autoDeploy: yes

  - type: postgres
    name: truckbrand-db
    plan: free
    databaseName: truckbrand
    user: truckbrand_user
  #   ipAllowList: []
  #   autoUpgrade: true
  #   maintenanceWindow: saturday-23:00-UTC
